### ISSUE TITLE
Failure: System down

### ISSUE THREAD

**Issue by Engineering-is-fun** [OpenBCI/Docs#121]
If anyone can help.

There is a communication problem between the dongle and the cyton. I have downloaded the lastest software and looked at multiple sources and could not resolve this issue.

**Comment by Chamikajp** [comment]
Did you do any firmware updates?

**Comment by biomurph** [comment]
Yes, we do firmware updates. Please visit our tutorials page to learn how to update your system
http://docs.openbci.com/Hardware/01-OpenBCI_Hardware

**Comment by daniellasry** [comment]
It's possible this was a firmware issue as mentioned. It's also possible that the dongle and Cyton were on different channels. In that case, simply hitting "AUTOSCAN" would solve the problem. 

I have opened issues #155 and OpenBCI/OpenBCI_GUI#418 to help with this.

I am closing this issue due to it's age, but please open a new one if you're still having trouble.
